version: '3.8'

services:
  backend:
    container_name: banco
    image: node:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh -c "npm run dev"